### ISSUE TITLE
Error in zone.js: More tasks executed then were scheduled.

### ISSUE THREAD

**Issue by ilaborie** [Stabzs/Angular2-Toaster#10]
When I run a toaster it's working but it is also trigger an error in zone.js
I'm using:
* Angular2 beta14
* angular2-toaster 0.2.0-beta.0
* RxJS 5.0.0-beta.2
* zone.js 0.6.11

```
browser_adapter.ts:73 Error: More tasks executed then were scheduled.
    at ZoneDelegate._updateTaskCount (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:398:24)
    at ZoneDelegate.invokeTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:369:27)
    at Zone.runTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:263:48)
    at ZoneTask.invoke (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:431:34)
  -------------   Elapsed: 5004 ms; At: Fri Apr 15 2016 08:17:01 GMT+0200 (CEST)   -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:1354:23)
    at ZoneDelegate.scheduleTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:342:50)
    at Zone.scheduleMacroTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:283:40)
    at https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:133:26
    at setTimeout (eval at createNamedFn (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:973:18), <anonymous>:3:37)
    at ToasterContainerComponent.configureTimer (http://localhost:8000/node_modules/angular2-toaster/lib/toaster-container.component.js:136:38)
    at ToasterContainerComponent.addToast (http://localhost:8000/node_modules/angular2-toaster/lib/toaster-container.component.js:113:14)
    at SafeSubscriber.eval [as _next] (http://localhost:8000/node_modules/angular2-toaster/lib/toaster-container.component.js:70:19)
  -------------   Elapsed: 2 ms; At: Fri Apr 15 2016 08:17:01 GMT+0200 (CEST)   -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:1354:23)
    at ZoneDelegate.scheduleTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:342:50)
    at Zone.scheduleMacroTask (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:283:40)
    at https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:133:26
    at setTimeout (eval at createNamedFn (https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js:973:18), <anonymous>:3:37)
    at ToasterService.popAsync (http://localhost:8000/node_modules/angular2-toaster/lib/toaster.service.js:31:9)
    at Home.ok (http://localhost:8000/app/mysew-app.js:63:35)
    at AbstractChangeDetector.ChangeDetector_Home_0.handleEventInternal (viewFactory_Home:131:21)
```

**Comment by xhite** [comment]
Looks like it's fixed in Angular2 beta 15

**Comment by Stabzs** [comment]
@ilaborie Can you please confirm if the error persists after upgrading to Angular2 beta 15?  This should be an issue with zone.js/Angular2, not the toaster library.

**Comment by ilaborie** [comment]
@Stabzs It's ok, with the beta 15 there is no error.
It was probably an issue fixed with the zone.js 6.10.0

**Comment by Stabzs** [comment]
Thank you for confirming!
