### ISSUE TITLE
Not woring on angular 8 ssr(server side rendering)

### ISSUE THREAD

**Issue by DimitrijeJankovic** [Stabzs/Angular2-Toaster#199]
> node dist/server

/Users/<user>/Documents/ds-web/node_modules/angular2-toaster/src/toaster-container.component.js:10
import { Component, Input, ChangeDetectorRef, NgZone } from '@angular/core';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ds-web@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ds-web@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2020-02-23T20_53_23_588Z-debug.log

**Comment by Stabzs** [comment]
The library has been republished under version 10.0.0.  If this is still an issue in version 10, please reopen the issue.  Thanks!
